"""initial schema

Revision ID: 1c0dd4d674f6
Revises: 
Create Date: 2026-09-14 15:24:35.847566
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1c0dd4d674f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('project_type', sa.String(length=64), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('current_system', sa.Text(), nullable=True),
    sa.Column('desired_outcome', sa.Text(), nullable=True),
    sa.Column('timeline', sa.String(length=64), nullable=True),
    sa.Column('budget_range', sa.String(length=64), nullable=True),
    sa.Column('additional', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=False),
    sa.Column('notified', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_submissions_email'), ['email'], unique=False)

    op.create_table('research_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_entries_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('websites',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_websites_host'), ['host'], unique=True)

    op.create_table('audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('website_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audits_website_id'), ['website_id'], unique=False)

    op.create_table('monitoring_targets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_response_ms', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ssl_valid', sa.Integer(), nullable=True),
    sa.Column('ssl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ssl_issuer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_targets_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_targets_user_id'), ['user_id'], unique=False)

    op.create_table('tool_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=False),
    sa.Column('result_meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_runs_tool'), ['tool'], unique=False)

    op.create_table('audit_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('audit_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_results_audit_id'), ['audit_id'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('audit_id', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_audit_id'), ['audit_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('audit_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('issue_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_audit_id'), ['audit_id'], unique=False)

    op.create_table('signal_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_events_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_signal_events_target_created', ['target_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_events_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_events_target_id'))
        batch_op.drop_index('ix_signal_events_target_created')
        batch_op.drop_index(batch_op.f('ix_signal_events_kind'))
        batch_op.drop_index(batch_op.f('ix_signal_events_created_at'))

    op.drop_table('signal_events')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_audit_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_audit_id'))

    op.drop_table('issues')
    with op.batch_alter_table('audit_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_results_audit_id'))

    op.drop_table('audit_results')
    with op.batch_alter_table('tool_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_runs_tool'))
        batch_op.drop_index(batch_op.f('ix_tool_runs_created_at'))

    op.drop_table('tool_runs')
    with op.batch_alter_table('monitoring_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_targets_user_id'))
        batch_op.drop_index(batch_op.f('ix_monitoring_targets_host'))

    op.drop_table('monitoring_targets')
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audits_website_id'))
        batch_op.drop_index(batch_op.f('ix_audits_user_id'))
        batch_op.drop_index(batch_op.f('ix_audits_status'))
        batch_op.drop_index(batch_op.f('ix_audits_created_at'))

    op.drop_table('audits')
    with op.batch_alter_table('websites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_websites_host'))

    op.drop_table('websites')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('research_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_entries_slug'))

    op.drop_table('research_entries')
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_submissions_email'))
        batch_op.drop_index(batch_op.f('ix_contact_submissions_created_at'))

    op.drop_table('contact_submissions')
    # ### end Alembic commands ###
