"""monitoring target source

Revision ID: c0a23653d173
Revises: 1c0dd4d674f6
Create Date: 2026-09-14 15:44:39.544929
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c0a23653d173'
down_revision = '1c0dd4d674f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), nullable=False, server_default='admin'))
        batch_op.create_index(batch_op.f('ix_monitoring_targets_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_targets_source'))
        batch_op.drop_column('source')

    # ### end Alembic commands ###
